config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      this_repo:
        commands:
        - git rev-parse --is-inside-work-tree
        container: qc.acc_slaphappy-goldenrod-tamarin
  QC.Doc:
    repos:
      this_repo:
        commands:
        - rst-lint --level warning --format json . docs
        container: qc.doc_slimy-goldenrod-llama
  QC.Lic:
    repos:
      this_repo:
        commands:
        - licensee detect . --json
        container: qc.lic_snazzy-vermilion-forest
      this_repo__2:
        commands:
        - licensee detect . --json
        container: qc.lic_fuzzy-coral-magpie
  QC.Sty:
    repos:
      this_repo:
        commands:
        - flake8 .
        container: qc.sty_skanky-amber-affenpinscher
timeout: 600
